name: lifemaker
description: Lifemaker Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  awesome_dialog: ^3.1.0
  bloc: ^8.1.2
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.6
  dropdown_textfield: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.13
  flutter_localizations:
    sdk: flutter
  flutter_offline: ^3.0.0
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  intl: ^0.18.1
  network_info_plus: ^4.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  pro_shered_preference: ^0.0.7
  screenshot: ^2.1.0
  share: ^2.0.4
  shared_preferences: ^2.2.1
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^16.1.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  #  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Alamiri
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf

#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
